AWSTemplateFormatVersion: 2010-09-09
Description: The SmartOffice DynamoDB-Table Stack

Parameters:
  microserviceName:
    Type: String
  ddbReadCapUnits:
    Type: String
  ddbWriteCapUnits:
    Type: String
  Stage:
    Type: String

Resources: 
  ddbTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "partitionkey"
          AttributeType: "S"
        - AttributeName: "sortkey"
          AttributeType: "S"  

      KeySchema: 
        - AttributeName: "partitionkey"
          KeyType: "HASH"
        - AttributeName: "sortkey"
          KeyType: "RANGE"  
      ProvisionedThroughput: 
        ReadCapacityUnits: !Sub "${ddbReadCapUnits}"
        WriteCapacityUnits: !Sub "${ddbWriteCapUnits}"
      TableName: !Sub "${microserviceName}-${AWS::StackName}-table-${Stage}"

Outputs:
  DDBTableArnOutput:
    Description: ARN of the DynamoDbTable
    Value: !GetAtt ddbTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}:arn"

